import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { PATHS } from '../paths';

const ENV_FILE = resolve(PATHS.EXAMPLE_APP, '.env');

const ENV_KEYS = ['CAPACITOR_SERVER_IP', 'CAPACITOR_SERVER_PORT', 'CAPACITOR_PLATFORM', 'EMULATOR_AVDS'] as const;

type EnvKey = (typeof ENV_KEYS)[number];
export type EnvVars = Partial<Record<EnvKey, string>>;

function parseEnvFile(content: string): EnvVars {
  const env: EnvVars = {};
  const validKeys = new Set<string>(ENV_KEYS);

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx <= 0) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();

    if (validKeys.has(key)) {
      env[key as EnvKey] = value;
    }
  }

  return env;
}

export function getEnv(): EnvVars {
  if (!existsSync(ENV_FILE)) return {};
  return parseEnvFile(readFileSync(ENV_FILE, 'utf-8'));
}

export function saveEnv(env: EnvVars): void {
  const lines = [
    '# Auto-generated by scripts/dev.ts',
    ...ENV_KEYS.filter((key) => env[key]).map((key) => `${key}=${env[key]}`),
  ];

  writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
}
