import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { PATHS } from './paths';

const ENV_FILE = resolve(PATHS.EXAMPLE_APP, '.env');

interface EnvVars {
  CAPACITOR_SERVER_IP?: string;
  CAPACITOR_SERVER_PORT?: string;
  CAPACITOR_PLATFORM?: string;
}

export function getEnv(): EnvVars {
  if (existsSync(ENV_FILE)) {
    const content = readFileSync(ENV_FILE, 'utf-8');
    const env: EnvVars = {};
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx > 0) {
          const key = trimmed.slice(0, eqIdx).trim();
          const value = trimmed.slice(eqIdx + 1).trim();
          if (key === 'CAPACITOR_SERVER_IP') env.CAPACITOR_SERVER_IP = value;
          if (key === 'CAPACITOR_SERVER_PORT') env.CAPACITOR_SERVER_PORT = value;
          if (key === 'CAPACITOR_PLATFORM') env.CAPACITOR_PLATFORM = value;
        }
      }
    }
    return env;
  }
  return {};
}

export function saveEnv(env: EnvVars): void {
  const lines: string[] = ['# Auto-generated by scripts/dev.ts'];
  if (env.CAPACITOR_SERVER_IP) {
    lines.push(`CAPACITOR_SERVER_IP=${env.CAPACITOR_SERVER_IP}`);
  }
  if (env.CAPACITOR_SERVER_PORT) {
    lines.push(`CAPACITOR_SERVER_PORT=${env.CAPACITOR_SERVER_PORT}`);
  }
  if (env.CAPACITOR_PLATFORM) {
    lines.push(`CAPACITOR_PLATFORM=${env.CAPACITOR_PLATFORM}`);
  }
  writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
}
